server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: bob
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  flyway:
    baseline-on-migrate: true

